config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#landing"
  resources :albums,  only: [:index, :show] do
    resources :reviews, only: [:new, :create]
  end
  resources :artists, only: [:index, :show], param: :artist_name

  resources :users, only: [:new, :create, :update]
  resource :cart

  resources :orders, only: [:new, :show, :create, :index]

  get "/dashboard",      to: "users#show"
  get "/dashboard/edit", to: "users#edit",  as: "user_edit"

  get "/login",     to: "sessions#new"
  post "/login",    to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/:genre",    to: "genres#show",  as: "genre"

  namespace :admin do
    resource  :dashboard, only: [:show]
    resource  :info,      only: [:edit, :update]
    resources :albums,    only: [:index, :new, :create, :edit, :update]
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper

  has_many :album_reviews
  has_many :reviews, through: :album_reviews

  belongs_to :artist
  belongs_to :genre

  has_many :order_albums
  has_many :orders, through: :order_albums

  validates :title,       presence: true, uniqueness: { scope: :artist_id }
  validates :description, presence: true
  validates :price,       presence: true
  validates :slug,        presence: true, uniqueness: true
  validates :expiry_date, presence: true

  def self.discovery(count)
    # unexpired_albums.limit(count).order("RANDOM()")
    unexpired_albums.sample(4)
  end

  def self.unexpired_albums
    all.reject(&:expired?)
  end

  def to_param
    slug
  end

  def formatted_price
    number_with_precision(price / 100.0, precision: 2)
  end

  def expired?
    Time.now > expiry_date
  end

  def status
    if expired?
      "Expired"
    else
      "Valid"
    end
  end
end

app/controllers/admin/albums_controller.rb
class Admin::AlbumsController < Admin::BaseController
  def index
    @albums = Album.all
  end

  def new
    @album   = Album.new
    @artists = Artist.all
    @genres  = Genre.all
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      flash[:message] = "#{@album.title} has been created"
      redirect_to admin_albums_path
    else
      @artists = Artist.all
      @genres  = Genre.all
      flash.now[:errors] = "Invalid Entry"
      render :new
    end
  end

  def edit
    @album = Album.find_by(slug: params[:id])
    @artists = Artist.all
    @genres = Genre.all
  end

  def update
    @album = Album.find_by(slug: params[:id])

    if @album.update(album_params)
      flash[:message] = "#{@album.title} has been edited"
      redirect_to admin_albums_path
    else
      @artists = Artist.all
      @genres = Genre.all
      flash.now[:errors] = "Invalid Entry"
      render :edit
    end
  end

  private

  def album_params
    params.require(:album).permit(:title, :slug, :artist_id, :genre_id, :description, :image_url, :release_year, :price, :expiry_date)
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @genres = Genre.all
    @albums = Album.unexpired_albums
    @featured_album = Album.take
  end

  def show
    @album = Album.find_by(slug: params[:id])
    @review = Review.new
  end
end

app/views/admin/albums/_form.html.erb
<%= form_for [:admin, @album] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :slug %>
  <%= f.text_field :slug %>
  <br>
  <%= f.label :artist_id %>
  <%= f.collection_select(:artist_id, @artists, :id, :name, { include_blank: 'Select an artist' }, { class: 'artistSelect' })  %>
  <br>
  <%= f.label :genre_id %>
  <%= f.collection_select(:genre_id, @genres, :id, :name, { include_blank: 'Select a genre' }, { class: 'genreSelect' }) %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :image_url %>
  <%= f.text_field :image_url %>

  <%= f.label :release_year %>
  <%= f.text_field :release_year %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.label :expiry_date %>
  <%= f.date_select :expiry_date %>

  <%= f.submit submit_name %>
<% end %>

app/views/admin/albums/edit.html.erb
<section class="container user-form-container">
  <h1>Edit Album</h1>

  <%= render "form", submit_name: "Edit Album" %>
</section>

app/views/admin/albums/index.html.erb
<section class="container section-container order-section">
  <h1>Albums Info</h1>

  <table class="admin-albums">
    <thead>
      <tr>
        <th class="ljust">Album</th>
        <th>Title</th>
        <th>Description</th>
        <th>Artist</th>
        <th>Status</th>
        <th>Edit</th>
      </tr>
    </thead>
    <tbody>
      <% @albums.each do |album| %>
        <tr>
          <td class="ljust"><%= link_to image_tag(album.image_url), album %></td>
          <td><%= link_to album.title, album_path(album) %></td>
          <td><%= album.description %></td>
          <td><%= link_to album.artist.name, album.artist %></td>
          <td><%= album.status %></td>
          <td><%= link_to "Edit", edit_admin_album_path(album) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= button_to "New Album", new_admin_album_path, method: :get %>
</section>

app/views/admin/albums/new.html.erb
<section class="container user-form-container">
  <h1>New Album</h1>

  <%= render "form", submit_name: "Create Album" %>
</section>