config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#landing"
  resources :albums,  only: [:index, :show] do
    resources :reviews, only: [:new, :create]
  end
  resources :artists, only: [:index, :show], param: :artist_name

  resources :users, only: [:new, :create, :update]
  resource :cart

  resources :orders, only: [:new, :show, :create, :index]

  get "/dashboard",      to: "users#show"
  get "/dashboard/edit", to: "users#edit",  as: "user_edit"

  get "/login",     to: "sessions#new"
  post "/login",    to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/:genre",    to: "genres#show",  as: "genre"

  namespace :admin do
    resource  :dashboard, only: [:show]
    resource  :info,      only: [:edit, :update]
    resources :albums,    only: [:index, :new, :create, :edit, :update]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :orders

  validates :username, presence: true, length: { minimum: 6 }, uniqueness: true
  validates :email, presence: true, format: { with: /@/ }, uniqueness: true

  enum role: ["default", "admin"]

  def authorize_session
    if admin?
      "/admin/dashboard"
    else
      "/dashboard"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      redirect_to dashboard_path
    else
      flash.now[:errors] = "Invalid Account Details"
      render :new
    end
  end

  def show
    if current_user.admin?
      redirect_to admin_dashboard_path
    else
      @user = current_user
    end
  end

  def edit
    @user = current_user
  end

  def update
    if current_user.update(user_params)
      flash[:info] = "Account updated!"
      redirect_to dashboard_path
    else
      @user = User.find(params[:id])
      flash.now[:errors] = "Invalid entry"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/views/users/edit.html.erb
<section class="container user-form-container">
  <h1>Update Account</h1>

  <%= form_for @user, url: user_path(@user) do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username, placeholder: "#{@user.username}" %>

    <%= f.label :email %>
    <%= f.email_field :email, placeholder: "#{@user.email}" %>

    <%= f.submit "Update Account" %>
  <% end %>
</section>

app/views/users/new.html.erb
<section class="container user-form-container">
  <h1>New User</h1>

  <%= form_for(@user) do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit "Create Account" %>
  <% end %>

  <small>Already a user? <%= link_to "Log in", login_path %></small>
</section>

app/views/users/show.html.erb
<%= render "shared/dashboard", dashboard_name: "Account Details" %>