config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#landing"
  resources :albums,  only: [:index, :show] do
    resources :reviews, only: [:new, :create]
  end
  resources :artists, only: [:index, :show], param: :artist_name

  resources :users, only: [:new, :create, :update]
  resource :cart

  resources :orders, only: [:new, :show, :create, :index]

  get "/dashboard",      to: "users#show"
  get "/dashboard/edit", to: "users#edit",  as: "user_edit"

  get "/login",     to: "sessions#new"
  post "/login",    to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/:genre",    to: "genres#show",  as: "genre"

  namespace :admin do
    resource  :dashboard, only: [:show]
    resource  :info,      only: [:edit, :update]
    resources :albums,    only: [:index, :new, :create, :edit, :update]
  end
end

app/views/shared/_dashboard.html.erb
<section class="container clearfix">
  <aside class="user-sidebar">
    <ul>
      <% if current_admin? %>
        <li><%= link_to "Account Details", admin_dashboard_path %></li>
        <li><%= link_to "Edit Account", edit_admin_info_path %></li>
        <li><%= link_to "Create New Album", new_admin_album_path %></li>
        <li><%= link_to "View Albums", admin_albums_path %></li>
      <% else %>
        <li><%= link_to "Account Details", dashboard_path %></li>
        <li><%= link_to "Update Account", user_edit_path %></li>
        <li><%= link_to "Past Orders", orders_path %></li>
      <% end %>
    </ul>
  </aside>

  <section class="user">
    <h1><%= dashboard_name %></h1>

    <ul>
      <li>
        Username: <%= current_user.username %>
      </li>
      <li>
        Email: <%= current_user.email %>
      </li>
    </ul>
  </section>
</section>