config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#landing"
  resources :albums,  only: [:index, :show] do
    resources :reviews, only: [:new, :create]
  end
  resources :artists, only: [:index, :show], param: :artist_name

  resources :users, only: [:new, :create, :update]
  resource :cart

  resources :orders, only: [:new, :show, :create, :index]

  get "/dashboard",      to: "users#show"
  get "/dashboard/edit", to: "users#edit",  as: "user_edit"

  get "/login",     to: "sessions#new"
  post "/login",    to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/:genre",    to: "genres#show",  as: "genre"

  namespace :admin do
    resource  :dashboard, only: [:show]
    resource  :info,      only: [:edit, :update]
    resources :albums,    only: [:index, :new, :create, :edit, :update]
  end
end

app/views/layouts/_footer.html.erb
<footer class="site-footer container clearfix">
  <small>&copy; 2016 Not Napster</small>

  <ul class="social-icons">
    <li><%= link_to image_tag("facebook.svg"), "#" %></li>
    <li><%= link_to image_tag("twitter.svg"), "#" %></li>
    <li><%= link_to image_tag("github.svg"), "https://github.com/scottfirestone/not_napster" %></li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<header class="site-header clearfix container">
  <%= link_to "Not Napster", root_path, class: "site-logo" %>

  <nav class="site-nav">
    <ul>
      <li><%= username(current_user) %></li>
      <li><%= link_to "Artists", artists_path %></li>
      <li><%= link_to "Albums", albums_path %></li>
      <!-- use path helper & glyphcon? -->
      <li><%= link_to "Cart #{@cart.navigation_quantity}", cart_path %></li>
      <li><%= login_logout_link(current_user) %></li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Not Napster</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link href='https://fonts.googleapis.com/css?family=Crimson+Text' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Julius+Sans+One' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>

  <% flash.each do |type, msg| %>
    <%= content_tag :div, msg, class: "#{type} flash" %>
  <% end %>

  <%= yield %>

  <%= render "layouts/footer" %>
</body>
</html>